/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ApproveEstimasiClientResult = IDL.Variant({
  'ok' : IDL.Text,
  'err' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AssignPartnerResult = IDL.Variant({
  'ok' : IDL.Text,
  'err' : IDL.Text,
});
export const FinancialResult = IDL.Record({
  'status' : IDL.Text,
  'platformFee' : IDL.Nat,
  'partnerReferralFee' : IDL.Nat,
  'taskId' : IDL.Text,
  'jamDibakar' : IDL.Nat,
  'jumlahBayar' : IDL.Nat,
  'partnerFee' : IDL.Nat,
});
export const CompleteTaskResult = IDL.Variant({
  'ok' : FinancialResult,
  'err' : IDL.Text,
});
export const CreateTaskResult = IDL.Variant({
  'ok' : IDL.Text,
  'err' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'requestedRole' : IDL.Opt(IDL.Text),
  'phoneNumber' : IDL.Opt(IDL.Text),
});
export const Layanan = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'active' : IDL.Null,
    'pendingApproval' : IDL.Null,
    'dormant' : IDL.Null,
    'depleted' : IDL.Null,
  }),
  'clientId' : IDL.Principal,
  'harga' : IDL.Nat,
  'nama' : IDL.Text,
  'createdAt' : IDL.Int,
  'deadline' : IDL.Int,
  'resourceType' : IDL.Variant({
    'dedicated' : IDL.Null,
    'standard' : IDL.Null,
  }),
  'adminId' : IDL.Principal,
  'scopeKerja' : IDL.Text,
  'layananType' : IDL.Variant({
    'reportWriting' : IDL.Null,
    'assistance' : IDL.Null,
    'dataEntry' : IDL.Null,
  }),
  'jamOnHold' : IDL.Nat,
  'saldoOriginal' : IDL.Nat,
  'saldoJamEfektif' : IDL.Nat,
});
export const InternalData = IDL.Record({
  'levelPartner' : IDL.Text,
  'jamEfektif' : IDL.Nat,
  'deadline' : IDL.Int,
  'partnerId' : IDL.Principal,
  'scopeKerja' : IDL.Text,
  'linkDriveInternal' : IDL.Text,
});
export const TaskClientView = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'clientId' : IDL.Principal,
  'internalData' : IDL.Opt(InternalData),
  'estimasiJam' : IDL.Nat,
  'judul' : IDL.Text,
  'linkDriveClient' : IDL.Opt(IDL.Text),
  'detailPermintaan' : IDL.Text,
  'layananId' : IDL.Text,
});
export const Status = IDL.Variant({
  'active' : IDL.Null,
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Role = IDL.Variant({
  'client' : IDL.Null,
  'admin' : IDL.Null,
  'finance' : IDL.Null,
  'strategicPartner' : IDL.Null,
  'concierge' : IDL.Null,
  'asistenmu' : IDL.Null,
  'superadmin' : IDL.Null,
  'partner' : IDL.Null,
});
export const User = IDL.Record({
  'status' : Status,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : Role,
  'email' : IDL.Opt(IDL.Text),
  'phoneNumber' : IDL.Opt(IDL.Text),
  'idUser' : IDL.Text,
  'companyBisnis' : IDL.Opt(IDL.Text),
  'principalId' : IDL.Principal,
  'kotaDomisili' : IDL.Opt(IDL.Text),
});
export const LayananClientView = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'unitAktif' : IDL.Nat,
  'harga' : IDL.Nat,
  'nama' : IDL.Text,
  'jumlahSharing' : IDL.Nat,
  'deadline' : IDL.Int,
  'saldo' : IDL.Nat,
  'scopeKerja' : IDL.Text,
  'jamOnHold' : IDL.Nat,
  'unitOnHold' : IDL.Nat,
  'namaAsistenmu' : IDL.Text,
  'saldoJamEfektif' : IDL.Nat,
});
export const InputEstimasiAMResult = IDL.Variant({
  'ok' : IDL.Text,
  'err' : IDL.Text,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const ResponPartnerResult = IDL.Variant({
  'ok' : IDL.Text,
  'err' : IDL.Text,
});
export const TaskStatus = IDL.Variant({
  'PendingPartner' : IDL.Null,
  'InQA' : IDL.Null,
  'ClientReview' : IDL.Null,
  'OnProgress' : IDL.Null,
  'Revision' : IDL.Null,
  'AwaitingClientApproval' : IDL.Null,
  'Requested' : IDL.Null,
  'RejectedByPartner' : IDL.Null,
  'Completed' : IDL.Null,
});
export const UpdateTaskStatusResult = IDL.Variant({
  'ok' : IDL.Text,
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPartnerBalance' : IDL.Func([IDL.Principal, IDL.Nat], [IDL.Text], []),
  'approveEstimasiClient' : IDL.Func(
      [IDL.Text],
      [ApproveEstimasiClientResult],
      [],
    ),
  'approveUser' : IDL.Func([IDL.Principal], [], []),
  'approveWithdraw' : IDL.Func([IDL.Text, IDL.Principal], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignPartner' : IDL.Func(
      [IDL.Text, IDL.Principal, IDL.Text, IDL.Int, IDL.Text, IDL.Nat, IDL.Text],
      [AssignPartnerResult],
      [],
    ),
  'claimSuperadmin' : IDL.Func([], [], []),
  'completeTask' : IDL.Func([IDL.Text], [CompleteTaskResult], []),
  'createTask' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, IDL.Text],
      [CreateTaskResult],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClientMainService' : IDL.Func([], [IDL.Opt(Layanan)], ['query']),
  'getClientTasks' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(TaskClientView)],
      ['query'],
    ),
  'getCurrentUser' : IDL.Func([], [IDL.Opt(User)], ['query']),
  'getMyLayananAktif' : IDL.Func([], [IDL.Vec(LayananClientView)], ['query']),
  'getPendingRequests' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(User)], ['query']),
  'inputEstimasiAM' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [InputEstimasiAMResult],
      [],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'registerInternalStaff' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'rejectUser' : IDL.Func([IDL.Principal], [], []),
  'rejectWithdraw' : IDL.Func([IDL.Text, IDL.Principal], [IDL.Text], []),
  'requestApproval' : IDL.Func([], [], []),
  'requestWithdraw' : IDL.Func([IDL.Principal, IDL.Nat], [IDL.Text], []),
  'responPartner' : IDL.Func([IDL.Text, IDL.Bool], [ResponPartnerResult], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'selfRegisterClient' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'selfRegisterInternal' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'selfRegisterPartner' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'updateProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateTaskStatus' : IDL.Func(
      [IDL.Text, TaskStatus],
      [UpdateTaskStatusResult],
      [],
    ),
  'updateUserRole' : IDL.Func([IDL.Principal, Role], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ApproveEstimasiClientResult = IDL.Variant({
    'ok' : IDL.Text,
    'err' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AssignPartnerResult = IDL.Variant({
    'ok' : IDL.Text,
    'err' : IDL.Text,
  });
  const FinancialResult = IDL.Record({
    'status' : IDL.Text,
    'platformFee' : IDL.Nat,
    'partnerReferralFee' : IDL.Nat,
    'taskId' : IDL.Text,
    'jamDibakar' : IDL.Nat,
    'jumlahBayar' : IDL.Nat,
    'partnerFee' : IDL.Nat,
  });
  const CompleteTaskResult = IDL.Variant({
    'ok' : FinancialResult,
    'err' : IDL.Text,
  });
  const CreateTaskResult = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'requestedRole' : IDL.Opt(IDL.Text),
    'phoneNumber' : IDL.Opt(IDL.Text),
  });
  const Layanan = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'active' : IDL.Null,
      'pendingApproval' : IDL.Null,
      'dormant' : IDL.Null,
      'depleted' : IDL.Null,
    }),
    'clientId' : IDL.Principal,
    'harga' : IDL.Nat,
    'nama' : IDL.Text,
    'createdAt' : IDL.Int,
    'deadline' : IDL.Int,
    'resourceType' : IDL.Variant({
      'dedicated' : IDL.Null,
      'standard' : IDL.Null,
    }),
    'adminId' : IDL.Principal,
    'scopeKerja' : IDL.Text,
    'layananType' : IDL.Variant({
      'reportWriting' : IDL.Null,
      'assistance' : IDL.Null,
      'dataEntry' : IDL.Null,
    }),
    'jamOnHold' : IDL.Nat,
    'saldoOriginal' : IDL.Nat,
    'saldoJamEfektif' : IDL.Nat,
  });
  const InternalData = IDL.Record({
    'levelPartner' : IDL.Text,
    'jamEfektif' : IDL.Nat,
    'deadline' : IDL.Int,
    'partnerId' : IDL.Principal,
    'scopeKerja' : IDL.Text,
    'linkDriveInternal' : IDL.Text,
  });
  const TaskClientView = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'clientId' : IDL.Principal,
    'internalData' : IDL.Opt(InternalData),
    'estimasiJam' : IDL.Nat,
    'judul' : IDL.Text,
    'linkDriveClient' : IDL.Opt(IDL.Text),
    'detailPermintaan' : IDL.Text,
    'layananId' : IDL.Text,
  });
  const Status = IDL.Variant({
    'active' : IDL.Null,
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Role = IDL.Variant({
    'client' : IDL.Null,
    'admin' : IDL.Null,
    'finance' : IDL.Null,
    'strategicPartner' : IDL.Null,
    'concierge' : IDL.Null,
    'asistenmu' : IDL.Null,
    'superadmin' : IDL.Null,
    'partner' : IDL.Null,
  });
  const User = IDL.Record({
    'status' : Status,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : Role,
    'email' : IDL.Opt(IDL.Text),
    'phoneNumber' : IDL.Opt(IDL.Text),
    'idUser' : IDL.Text,
    'companyBisnis' : IDL.Opt(IDL.Text),
    'principalId' : IDL.Principal,
    'kotaDomisili' : IDL.Opt(IDL.Text),
  });
  const LayananClientView = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'unitAktif' : IDL.Nat,
    'harga' : IDL.Nat,
    'nama' : IDL.Text,
    'jumlahSharing' : IDL.Nat,
    'deadline' : IDL.Int,
    'saldo' : IDL.Nat,
    'scopeKerja' : IDL.Text,
    'jamOnHold' : IDL.Nat,
    'unitOnHold' : IDL.Nat,
    'namaAsistenmu' : IDL.Text,
    'saldoJamEfektif' : IDL.Nat,
  });
  const InputEstimasiAMResult = IDL.Variant({
    'ok' : IDL.Text,
    'err' : IDL.Text,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const ResponPartnerResult = IDL.Variant({
    'ok' : IDL.Text,
    'err' : IDL.Text,
  });
  const TaskStatus = IDL.Variant({
    'PendingPartner' : IDL.Null,
    'InQA' : IDL.Null,
    'ClientReview' : IDL.Null,
    'OnProgress' : IDL.Null,
    'Revision' : IDL.Null,
    'AwaitingClientApproval' : IDL.Null,
    'Requested' : IDL.Null,
    'RejectedByPartner' : IDL.Null,
    'Completed' : IDL.Null,
  });
  const UpdateTaskStatusResult = IDL.Variant({
    'ok' : IDL.Text,
    'err' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPartnerBalance' : IDL.Func([IDL.Principal, IDL.Nat], [IDL.Text], []),
    'approveEstimasiClient' : IDL.Func(
        [IDL.Text],
        [ApproveEstimasiClientResult],
        [],
      ),
    'approveUser' : IDL.Func([IDL.Principal], [], []),
    'approveWithdraw' : IDL.Func([IDL.Text, IDL.Principal], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignPartner' : IDL.Func(
        [
          IDL.Text,
          IDL.Principal,
          IDL.Text,
          IDL.Int,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
        ],
        [AssignPartnerResult],
        [],
      ),
    'claimSuperadmin' : IDL.Func([], [], []),
    'completeTask' : IDL.Func([IDL.Text], [CompleteTaskResult], []),
    'createTask' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, IDL.Text],
        [CreateTaskResult],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClientMainService' : IDL.Func([], [IDL.Opt(Layanan)], ['query']),
    'getClientTasks' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(TaskClientView)],
        ['query'],
      ),
    'getCurrentUser' : IDL.Func([], [IDL.Opt(User)], ['query']),
    'getMyLayananAktif' : IDL.Func([], [IDL.Vec(LayananClientView)], ['query']),
    'getPendingRequests' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(User)], ['query']),
    'inputEstimasiAM' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [InputEstimasiAMResult],
        [],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'registerInternalStaff' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'rejectUser' : IDL.Func([IDL.Principal], [], []),
    'rejectWithdraw' : IDL.Func([IDL.Text, IDL.Principal], [IDL.Text], []),
    'requestApproval' : IDL.Func([], [], []),
    'requestWithdraw' : IDL.Func([IDL.Principal, IDL.Nat], [IDL.Text], []),
    'responPartner' : IDL.Func([IDL.Text, IDL.Bool], [ResponPartnerResult], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'selfRegisterClient' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'selfRegisterInternal' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'selfRegisterPartner' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'updateProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateTaskStatus' : IDL.Func(
        [IDL.Text, TaskStatus],
        [UpdateTaskStatusResult],
        [],
      ),
    'updateUserRole' : IDL.Func([IDL.Principal, Role], [], []),
  });
};

export const init = ({ IDL }) => { return []; };