/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'requestedRole' : IDL.Opt(IDL.Text),
});
export const Status = IDL.Variant({
  'active' : IDL.Null,
  'pending' : IDL.Null,
});
export const Role = IDL.Variant({
  'client' : IDL.Null,
  'admin' : IDL.Null,
  'finance' : IDL.Null,
  'strategicPartner' : IDL.Null,
  'concierge' : IDL.Null,
  'asistenmu' : IDL.Null,
  'superadmin' : IDL.Null,
  'partner' : IDL.Null,
});
export const User = IDL.Record({
  'status' : Status,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : Role,
  'principalId' : IDL.Principal,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveUser' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimSuperadmin' : IDL.Func([], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentUser' : IDL.Func([], [IDL.Opt(User)], ['query']),
  'getPendingRequests' : IDL.Func([], [IDL.Vec(User)], ['query']),
  'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(User)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'registerInternalStaff' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'rejectUser' : IDL.Func([IDL.Principal], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'selfRegisterClient' : IDL.Func([IDL.Text], [], []),
  'selfRegisterInternal' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'selfRegisterPartner' : IDL.Func([IDL.Text], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'requestedRole' : IDL.Opt(IDL.Text),
  });
  const Status = IDL.Variant({ 'active' : IDL.Null, 'pending' : IDL.Null });
  const Role = IDL.Variant({
    'client' : IDL.Null,
    'admin' : IDL.Null,
    'finance' : IDL.Null,
    'strategicPartner' : IDL.Null,
    'concierge' : IDL.Null,
    'asistenmu' : IDL.Null,
    'superadmin' : IDL.Null,
    'partner' : IDL.Null,
  });
  const User = IDL.Record({
    'status' : Status,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : Role,
    'principalId' : IDL.Principal,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveUser' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimSuperadmin' : IDL.Func([], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentUser' : IDL.Func([], [IDL.Opt(User)], ['query']),
    'getPendingRequests' : IDL.Func([], [IDL.Vec(User)], ['query']),
    'getUserProfile' : IDL.Func([IDL.Principal], [IDL.Opt(User)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'registerInternalStaff' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'rejectUser' : IDL.Func([IDL.Principal], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'selfRegisterClient' : IDL.Func([IDL.Text], [], []),
    'selfRegisterInternal' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'selfRegisterPartner' : IDL.Func([IDL.Text], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };